import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getSession } from '@/lib/auth';
import { generateTrackingNumber, generateQRCode, ShipmentStatus } from '@/lib/shipping';

export async function POST(req: NextRequest) {
    try {
        const session = await getSession();
        if (!session) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { transactionId } = await req.json();
        if (!transactionId) {
            return NextResponse.json({ error: 'Transaction ID is required' }, { status: 400 });
        }

        // Fetch transaction details
        const transaction = await prisma.transaction.findUnique({
            where: { id: transactionId },
            include: {
                listing: true,
                buyer: true,
                seller: true
            }
        });

        if (!transaction) {
            return NextResponse.json({ error: 'Transaction not found' }, { status: 404 });
        }

        // Verify user is the seller
        if (transaction.sellerId !== session) {
            return NextResponse.json({ error: 'Only the seller can generate a shipping label' }, { status: 403 });
        }

        // Check if label already exists
        const existingLabel = await prisma.shippingLabel.findUnique({
            where: { transactionId }
        });

        if (existingLabel) {
            return NextResponse.json(existingLabel);
        }

        // Generate new label data
        const trackingNumber = generateTrackingNumber();

        // QR Code Data
        const qrData = {
            tn: trackingNumber,
            s: transaction.sellerId,
            b: transaction.buyerId,
            cod: transaction.paymentMethod === 'COD' ? transaction.amount : 0
        };

        const qrCode = await generateQRCode(qrData);

        // Create Shipping Label
        const label = await prisma.shippingLabel.create({
            data: {
                trackingNumber,
                transactionId,
                carrier: transaction.shippingMethod || 'AMANA',
                pickupAddress: transaction.seller.address || {}, // Assuming address exists on User, fallback to empty
                deliveryAddress: transaction.shippingAddress || {},
                declaredValue: transaction.amount,
                qrCode,
                status: ShipmentStatus.PENDING_PICKUP,
                statusHistory: [
                    {
                        status: ShipmentStatus.PENDING_PICKUP,
                        timestamp: new Date().toISOString(),
                        notes: 'Label generated by seller'
                    }
                ]
            }
        });

        // Update Transaction with tracking info
        await prisma.transaction.update({
            where: { id: transactionId },
            data: {
                trackingNumber,
                shipmentStatus: 'PENDING_SHIPMENT'
            }
        });

        return NextResponse.json(label);

    } catch (error) {
        console.error('Error generating shipping label:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
