export const brands = [
    // Luxury Brands
    { name: 'Gucci', slug: 'gucci', category: 'luxury', verified: true, popular: true },
    { name: 'Louis Vuitton', slug: 'louis-vuitton', category: 'luxury', verified: true, popular: true },
    { name: 'Hermès', slug: 'hermes', category: 'luxury', verified: true, popular: true },
    { name: 'Chanel', slug: 'chanel', category: 'luxury', verified: true, popular: true },
    { name: 'Dior', slug: 'dior', category: 'luxury', verified: true, popular: true },
    { name: 'Prada', slug: 'prada', category: 'luxury', verified: true, popular: true },
    { name: 'Fendi', slug: 'fendi', category: 'luxury', verified: true, popular: true },
    { name: 'Balenciaga', slug: 'balenciaga', category: 'luxury', verified: true, popular: true },
    { name: 'Saint Laurent', slug: 'saint-laurent', category: 'luxury', verified: true, popular: true },
    { name: 'Valentino', slug: 'valentino', category: 'luxury', verified: true, popular: true },
    { name: 'Givenchy', slug: 'givenchy', category: 'luxury', verified: true, popular: true },
    { name: 'Bottega Veneta', slug: 'bottega-veneta', category: 'luxury', verified: true, popular: true },
    { name: 'Burberry', slug: 'burberry', category: 'luxury', verified: true, popular: true },
    { name: 'Versace', slug: 'versace', category: 'luxury', verified: true, popular: true },
    { name: 'Dolce & Gabbana', slug: 'dolce-gabbana', category: 'luxury', verified: true, popular: true },
    { name: 'Celine', slug: 'celine', category: 'luxury', verified: true, popular: true },
    { name: 'Loewe', slug: 'loewe', category: 'luxury', verified: true, popular: false },
    { name: 'Miu Miu', slug: 'miu-miu', category: 'luxury', verified: true, popular: false },

    // Designer Brands
    { name: 'Ralph Lauren', slug: 'ralph-lauren', category: 'designer', verified: true, popular: true },
    { name: 'Tommy Hilfiger', slug: 'tommy-hilfiger', category: 'designer', verified: true, popular: true },
    { name: 'Calvin Klein', slug: 'calvin-klein', category: 'designer', verified: true, popular: true },
    { name: 'Hugo Boss', slug: 'hugo-boss', category: 'designer', verified: true, popular: true },
    { name: 'Armani', slug: 'armani', category: 'designer', verified: true, popular: true },
    { name: 'Lacoste', slug: 'lacoste', category: 'designer', verified: true, popular: true },
    { name: 'Michael Kors', slug: 'michael-kors', category: 'designer', verified: true, popular: true },
    { name: 'Kate Spade', slug: 'kate-spade', category: 'designer', verified: true, popular: false },
    { name: 'Coach', slug: 'coach', category: 'designer', verified: true, popular: true },
    { name: 'Ted Baker', slug: 'ted-baker', category: 'designer', verified: true, popular: false },
    { name: 'Polo Ralph Lauren', slug: 'polo-ralph-lauren', category: 'designer', verified: true, popular: true },
    { name: 'Diesel', slug: 'diesel', category: 'designer', verified: true, popular: true },
    { name: 'Guess', slug: 'guess', category: 'designer', verified: true, popular: true },
    { name: 'Massimo Dutti', slug: 'massimo-dutti', category: 'designer', verified: true, popular: true },

    // Streetwear & Sports
    { name: 'Nike', slug: 'nike', category: 'streetwear', verified: true, popular: true },
    { name: 'Adidas', slug: 'adidas', category: 'streetwear', verified: true, popular: true },
    { name: 'Puma', slug: 'puma', category: 'streetwear', verified: true, popular: true },
    { name: 'New Balance', slug: 'new-balance', category: 'streetwear', verified: true, popular: true },
    { name: 'Reebok', slug: 'reebok', category: 'streetwear', verified: true, popular: true },
    { name: 'Converse', slug: 'converse', category: 'streetwear', verified: true, popular: true },
    { name: 'Vans', slug: 'vans', category: 'streetwear', verified: true, popular: true },
    { name: 'Supreme', slug: 'supreme', category: 'streetwear', verified: true, popular: true },
    { name: 'Off-White', slug: 'off-white', category: 'streetwear', verified: true, popular: true },
    { name: 'Stüssy', slug: 'stussy', category: 'streetwear', verified: true, popular: false },
    { name: 'Palace', slug: 'palace', category: 'streetwear', verified: true, popular: false },
    { name: 'The North Face', slug: 'the-north-face', category: 'streetwear', verified: true, popular: true },
    { name: 'Patagonia', slug: 'patagonia', category: 'streetwear', verified: true, popular: false },
    { name: 'Stone Island', slug: 'stone-island', category: 'streetwear', verified: true, popular: false },
    { name: 'Carhartt', slug: 'carhartt', category: 'streetwear', verified: true, popular: false },
    { name: 'Champion', slug: 'champion', category: 'streetwear', verified: true, popular: true },
    { name: 'Fila', slug: 'fila', category: 'streetwear', verified: true, popular: true },
    { name: 'Kappa', slug: 'kappa', category: 'streetwear', verified: true, popular: false },
    { name: 'Ellesse', slug: 'ellesse', category: 'streetwear', verified: true, popular: false },
    { name: 'Under Armour', slug: 'under-armour', category: 'streetwear', verified: true, popular: true },

    // Fast Fashion
    { name: 'Zara', slug: 'zara', category: 'fast-fashion', verified: true, popular: true },
    { name: 'H&M', slug: 'hm', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Mango', slug: 'mango', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Pull & Bear', slug: 'pull-bear', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Bershka', slug: 'bershka', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Stradivarius', slug: 'stradivarius', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Uniqlo', slug: 'uniqlo', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Forever 21', slug: 'forever-21', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Topshop', slug: 'topshop', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Topman', slug: 'topman', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Primark', slug: 'primark', category: 'fast-fashion', verified: true, popular: false },
    { name: 'New Look', slug: 'new-look', category: 'fast-fashion', verified: true, popular: false },
    { name: 'River Island', slug: 'river-island', category: 'fast-fashion', verified: true, popular: false },
    { name: 'GAP', slug: 'gap', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Old Navy', slug: 'old-navy', category: 'fast-fashion', verified: true, popular: false },
    { name: 'American Eagle', slug: 'american-eagle', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Aeropostale', slug: 'aeropostale', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Hollister', slug: 'hollister', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Abercrombie & Fitch', slug: 'abercrombie-fitch', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Urban Outfitters', slug: 'urban-outfitters', category: 'fast-fashion', verified: true, popular: false },
    { name: 'ASOS', slug: 'asos', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Boohoo', slug: 'boohoo', category: 'fast-fashion', verified: true, popular: false },
    { name: 'PrettyLittleThing', slug: 'prettylittlething', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Shein', slug: 'shein', category: 'fast-fashion', verified: true, popular: true },
    { name: 'C&A', slug: 'ca', category: 'fast-fashion', verified: true, popular: true },
    { name: 'Esprit', slug: 'esprit', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Promod', slug: 'promod', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Camaïeu', slug: 'camaieu', category: 'fast-fashion', verified: true, popular: false },
    { name: 'Kiabi', slug: 'kiabi', category: 'fast-fashion', verified: true, popular: true },

    // Moroccan & Local Brands
    { name: 'Caftan Marocain', slug: 'caftan-marocain', category: 'moroccan', verified: true, popular: true },
    { name: 'Jabador', slug: 'jabador', category: 'moroccan', verified: true, popular: true },
    { name: 'Takchita', slug: 'takchita', category: 'moroccan', verified: true, popular: true },
    { name: 'Artisanal Marocain', slug: 'artisanal-marocain', category: 'moroccan', verified: true, popular: false },

    // Premium Contemporary
    { name: 'Sandro', slug: 'sandro', category: 'designer', verified: true, popular: true },
    { name: 'Maje', slug: 'maje', category: 'designer', verified: true, popular: true },
    { name: 'Claudie Pierlot', slug: 'claudie-pierlot', category: 'designer', verified: true, popular: false },
    { name: 'Ba&sh', slug: 'bash', category: 'designer', verified: true, popular: false },
    { name: 'The Kooples', slug: 'the-kooples', category: 'designer', verified: true, popular: false },
    { name: 'Zadig & Voltaire', slug: 'zadig-voltaire', category: 'designer', verified: true, popular: false },
    { name: 'All Saints', slug: 'all-saints', category: 'designer', verified: true, popular: false },
    { name: 'Reiss', slug: 'reiss', category: 'designer', verified: true, popular: false },
    { name: 'COS', slug: 'cos', category: 'designer', verified: true, popular: true },
    { name: '& Other Stories', slug: 'other-stories', category: 'designer', verified: true, popular: false },
    { name: 'Monki', slug: 'monki', category: 'fast-fashion', verified: true, popular: false },

    // Denim Specialists
    { name: 'Levi\'s', slug: 'levis', category: 'designer', verified: true, popular: true },
    { name: 'Wrangler', slug: 'wrangler', category: 'designer', verified: true, popular: true },
    { name: 'Lee', slug: 'lee', category: 'designer', verified: true, popular: true },
    { name: 'G-Star RAW', slug: 'g-star-raw', category: 'designer', verified: true, popular: false },
    { name: 'True Religion', slug: 'true-religion', category: 'designer', verified: true, popular: false },
    { name: '7 For All Mankind', slug: '7-for-all-mankind', category: 'designer', verified: true, popular: false },
    { name: 'Acne Studios', slug: 'acne-studios', category: 'designer', verified: true, popular: false },

    // Activewear
    { name: 'Lululemon', slug: 'lululemon', category: 'streetwear', verified: true, popular: true },
    { name: 'Gymshark', slug: 'gymshark', category: 'streetwear', verified: true, popular: true },
    { name: 'Alo Yoga', slug: 'alo-yoga', category: 'streetwear', verified: true, popular: false },
    { name: 'Sweaty Betty', slug: 'sweaty-betty', category: 'streetwear', verified: true, popular: false },
    { name: 'Outdoor Voices', slug: 'outdoor-voices', category: 'streetwear', verified: true, popular: false },

    // Shoes
    { name: 'Dr. Martens', slug: 'dr-martens', category: 'streetwear', verified: true, popular: true },
    { name: 'Timberland', slug: 'timberland', category: 'streetwear', verified: true, popular: true },
    { name: 'UGG', slug: 'ugg', category: 'designer', verified: true, popular: true },
    { name: 'Birkenstock', slug: 'birkenstock', category: 'designer', verified: true, popular: true },
    { name: 'Clarks', slug: 'clarks', category: 'designer', verified: true, popular: true },
    { name: 'Steve Madden', slug: 'steve-madden', category: 'designer', verified: true, popular: false },
    { name: 'Sam Edelman', slug: 'sam-edelman', category: 'designer', verified: true, popular: false },
    { name: 'Aldo', slug: 'aldo', category: 'fast-fashion', verified: true, popular: true },

    // Accessories & Bags
    { name: 'Longchamp', slug: 'longchamp', category: 'designer', verified: true, popular: true },
    { name: 'Furla', slug: 'furla', category: 'designer', verified: true, popular: false },
    { name: 'Tory Burch', slug: 'tory-burch', category: 'designer', verified: true, popular: true },
    { name: 'Rebecca Minkoff', slug: 'rebecca-minkoff', category: 'designer', verified: true, popular: false },
    { name: 'MCM', slug: 'mcm', category: 'luxury', verified: true, popular: false },

    // Watches & Jewelry
    { name: 'Cartier', slug: 'cartier', category: 'luxury', verified: true, popular: true },
    { name: 'Rolex', slug: 'rolex', category: 'luxury', verified: true, popular: true },
    { name: 'Tiffany & Co', slug: 'tiffany-co', category: 'luxury', verified: true, popular: true },
    { name: 'Pandora', slug: 'pandora', category: 'designer', verified: true, popular: true },
    { name: 'Swarovski', slug: 'swarovski', category: 'designer', verified: true, popular: true },
    { name: 'Daniel Wellington', slug: 'daniel-wellington', category: 'designer', verified: true, popular: false },
    { name: 'Fossil', slug: 'fossil', category: 'designer', verified: true, popular: true },
    { name: 'Michael Kors Watches', slug: 'michael-kors-watches', category: 'designer', verified: true, popular: true },

    // Others
    { name: 'Other', slug: 'other', category: 'other', verified: false, popular: false },
];
