export const sizes = [
    // CLOTHING - International Sizes (Unisex)
    { value: 'XXS', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 0 },
    { value: 'XS', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 1 },
    { value: 'S', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 2 },
    { value: 'M', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 3 },
    { value: 'L', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 4 },
    { value: 'XL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 5 },
    { value: 'XXL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 6 },
    { value: 'XXXL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'tops', sortOrder: 7 },

    // CLOTHING - International Sizes for Bottoms
    { value: 'XXS', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 0 },
    { value: 'XS', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 1 },
    { value: 'S', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 2 },
    { value: 'M', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 3 },
    { value: 'L', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 4 },
    { value: 'XL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 5 },
    { value: 'XXL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 6 },
    { value: 'XXXL', system: 'INT', category: 'clothing', gender: 'unisex', itemType: 'bottoms', sortOrder: 7 },

    // CLOTHING - EU Sizes Women
    { value: '32', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 32 },
    { value: '34', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 34 },
    { value: '36', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 36 },
    { value: '38', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 38 },
    { value: '40', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 40 },
    { value: '42', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 42 },
    { value: '44', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 44 },
    { value: '46', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 46 },
    { value: '48', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 48 },
    { value: '50', system: 'EU', category: 'clothing', gender: 'women', itemType: null, sortOrder: 50 },

    // CLOTHING - EU Sizes Men
    { value: '44', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 44 },
    { value: '46', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 46 },
    { value: '48', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 48 },
    { value: '50', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 50 },
    { value: '52', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 52 },
    { value: '54', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 54 },
    { value: '56', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 56 },
    { value: '58', system: 'EU', category: 'clothing', gender: 'men', itemType: null, sortOrder: 58 },

    // CLOTHING - US Sizes Women
    { value: '0', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 0 },
    { value: '2', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 2 },
    { value: '4', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 4 },
    { value: '6', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 6 },
    { value: '8', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 8 },
    { value: '10', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 10 },
    { value: '12', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 12 },
    { value: '14', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 14 },
    { value: '16', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 16 },
    { value: '18', system: 'US', category: 'clothing', gender: 'women', itemType: null, sortOrder: 18 },

    // CLOTHING - UK Sizes Women
    { value: '4', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 4 },
    { value: '6', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 6 },
    { value: '8', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 8 },
    { value: '10', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 10 },
    { value: '12', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 12 },
    { value: '14', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 14 },
    { value: '16', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 16 },
    { value: '18', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 18 },
    { value: '20', system: 'UK', category: 'clothing', gender: 'women', itemType: null, sortOrder: 20 },

    // SHOES - EU Sizes
    { value: '35', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 35 },
    { value: '35.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 35.5 },
    { value: '36', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 36 },
    { value: '36.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 36.5 },
    { value: '37', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 37 },
    { value: '37.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 37.5 },
    { value: '38', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 38 },
    { value: '38.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 38.5 },
    { value: '39', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 39 },
    { value: '39.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 39.5 },
    { value: '40', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 40 },
    { value: '40.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 40.5 },
    { value: '41', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 41 },
    { value: '41.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 41.5 },
    { value: '42', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 42 },
    { value: '42.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 42.5 },
    { value: '43', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 43 },
    { value: '43.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 43.5 },
    { value: '44', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 44 },
    { value: '44.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 44.5 },
    { value: '45', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 45 },
    { value: '45.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 45.5 },
    { value: '46', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 46 },
    { value: '46.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 46.5 },
    { value: '47', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 47 },
    { value: '47.5', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 47.5 },
    { value: '48', system: 'EU', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 48 },

    // SHOES - US Sizes Men
    { value: '6', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 6 },
    { value: '6.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 6.5 },
    { value: '7', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 7 },
    { value: '7.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 7.5 },
    { value: '8', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 8 },
    { value: '8.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 8.5 },
    { value: '9', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 9 },
    { value: '9.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 9.5 },
    { value: '10', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 10 },
    { value: '10.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 10.5 },
    { value: '11', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 11 },
    { value: '11.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 11.5 },
    { value: '12', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 12 },
    { value: '12.5', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 12.5 },
    { value: '13', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 13 },
    { value: '14', system: 'US', category: 'shoes', gender: 'men', itemType: 'shoes', sortOrder: 14 },

    // SHOES - US Sizes Women
    { value: '5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 5 },
    { value: '5.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 5.5 },
    { value: '6', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 6 },
    { value: '6.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 6.5 },
    { value: '7', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 7 },
    { value: '7.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 7.5 },
    { value: '8', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 8 },
    { value: '8.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 8.5 },
    { value: '9', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 9 },
    { value: '9.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 9.5 },
    { value: '10', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 10 },
    { value: '10.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 10.5 },
    { value: '11', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 11 },
    { value: '11.5', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 11.5 },
    { value: '12', system: 'US', category: 'shoes', gender: 'women', itemType: 'shoes', sortOrder: 12 },

    // SHOES - UK Sizes
    { value: '3', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 3 },
    { value: '3.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 3.5 },
    { value: '4', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 4 },
    { value: '4.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 4.5 },
    { value: '5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 5 },
    { value: '5.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 5.5 },
    { value: '6', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 6 },
    { value: '6.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 6.5 },
    { value: '7', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 7 },
    { value: '7.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 7.5 },
    { value: '8', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 8 },
    { value: '8.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 8.5 },
    { value: '9', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 9 },
    { value: '9.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 9.5 },
    { value: '10', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 10 },
    { value: '10.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 10.5 },
    { value: '11', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 11 },
    { value: '11.5', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 11.5 },
    { value: '12', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 12 },
    { value: '13', system: 'UK', category: 'shoes', gender: null, itemType: 'shoes', sortOrder: 13 },

    // ACCESSORIES - One Size
    { value: 'One Size', system: 'INT', category: 'accessories', gender: null, itemType: null, sortOrder: 0 },
    { value: 'Adjustable', system: 'INT', category: 'accessories', gender: null, itemType: null, sortOrder: 1 },

    // KIDS - Age Based
    { value: '0-3M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 0 },
    { value: '3-6M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 1 },
    { value: '6-9M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 2 },
    { value: '9-12M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 3 },
    { value: '12-18M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 4 },
    { value: '18-24M', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 5 },
    { value: '2T', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 6 },
    { value: '3T', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 7 },
    { value: '4T', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 8 },
    { value: '5', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 9 },
    { value: '6', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 10 },
    { value: '7', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 11 },
    { value: '8', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 12 },
    { value: '10', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 13 },
    { value: '12', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 14 },
    { value: '14', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 15 },
    { value: '16', system: 'INT', category: 'clothing', gender: 'kids', itemType: null, sortOrder: 16 },
];
